CREATE TABLE IF NOT EXISTS DE_TAGS
  (id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  tag TEXT);

CREATE TABLE IF NOT EXISTS DE_BOOK_TAGS
  (id INTEGER PRIMARY KEY AUTOINCREMENT,
  book_uuid TEXT,
  tag_uuid TEXT,
  FOREIGN KEY(book_uuid) REFERENCES DE_BOOKS(uuid),
  FOREIGN KEY(tag_uuid) REFERENCES DE_TAGS(uuid));

CREATE TABLE IF NOT EXISTS DE_BOOKS
  (id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT,
  url TEXT,
  desc TEXT,
  added_at INTEGER);
